### ISSUE TITLE
Feature Request: Classes as mixins

### ISSUE THREAD

**Issue by matthewrobb** [WebReflection/es-class#2]
It would be great to be able to pass classes into the `with` list. Ideally this could result in both static and prototype members being copied over to the new class. I am not sure how simple this will be considering, from what I currently understand, ES6 class methods are non-enumerable by default and at a glance it looks like only enumerable ownProps get copied over in this project at the moment.

**Comment by WebReflection** [comment]
Using enumerable properties is not the problem, inheritance is.

If a class is passed as mixin/trait it might have inherited methods too so that walking through its prototype won't be enough.

I am still thinking if having classes as mixins/traits is a good pattern. Can you give one example where a class, as trait, is better than a plain object that provides a behavior?

Can you also please tell me if traits in ES7 have been discussed at all and these will be classes instead of traits?

This library/utility does not want to tell people classes as mixins are OK if then this won#t ever happen in the next version of JS, here is all about being close to the current and coming standard, without promoting or taking position on how that should be.

Lightweight traits are somehow OK as plain object now, since that's the most basic "behavior" you can describe in JS, classes are a different beast.

Thanks for collaboration!

**Comment by WebReflection** [comment]
Version `1.0.0` ships with the ability to mixin classes too.

Even vanilla functions work as expected, but in case you are targeting IE8 or lower, in this case vanilla functions might not bring in inherited properties.

All is good, as tests say, if you mixin a class created via es-class
